# netlify.toml

[build]
  publish = "/"  # Publish root directory since it's a simple static site

# Handle redirects for SPA and route all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable compression
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true 